CREATE DATABASE cs157a_ecommerce;
USE cs157a_ecommerce;
CREATE TABLE CUSTOMER (
  CUSTOMER_ID int AUTO_INCREMENT,
  FIRST_NAME varchar(15) NOT NULL,
  LAST_NAME varchar(15) NOT NULL,
  EMAIL varchar(30) NOT NULL UNIQUE,
  PASSWORD varchar(255) NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE SUPPLIER (
	SUPPLIER_ID int AUTO_INCREMENT,
	NAME varchar(50) NOT NULL,
	EMAIL varchar(30) NOT NULL,
	PRIMARY KEY (SUPPLIER_ID)
);
CREATE TABLE ADDRESS (
	ADDRESS_ID int AUTO_INCREMENT,
	CUSTOMER_ID int NULL,
	SUPPLIER_ID int NULL,
	ADDRESS_LINE1 varchar(50) NOT NULL,
	ADDRESS_LINE2 varchar(50) NULL,
	CITY varchar(30) NOT NULL,
	STATE varchar(50) NOT NULL,
	ZIP char(5) NOT NULL,
	COUNTRY varchar(50) NOT NULL,
	ADDRESS_TYPE varchar(10) NOT NULL,
	PRIMARY KEY (ADDRESS_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
	FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID)
);
CREATE TABLE ORDERS (
    ORDER_ID int AUTO_INCREMENT,
    CUSTOMER_ID int NOT NULL,
    SHIP_ADDRESS_ID int NOT NULL,
    DATE date,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    FOREIGN KEY (SHIP_ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID)
);
CREATE TABLE PRODUCT (
    PRODUCT_ID int NOT NULL UNIQUE,
    PRODUCT_NAME varchar(30) NOT NULL,
    PRODUCT_DESCRIPTION varchar(255) NOT NULL,
    SUPPLIER_ID int NOT NULL,
    PRICE double NOT NULL,
    QUANTITY int NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID)
);
CREATE TABLE PRODUCTS_ORDER (
    PRODUCTS_ORDER_ID int AUTO_INCREMENT,
    ORDER_ID int NOT NULL,
    PRODUCT_ID int NOT NULL,
    QUANTITY int NOT NULL,
    SUB_TOTAL double NOT NULL,
    PRIMARY KEY (PRODUCTS_ORDER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID)
);
exit
