version: '3.3'
services:
  db:
    image: linraymond/cs157a_sql_database_with_sample_data:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'cs157a_ecommerce'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'changeme-security'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'changeme-security'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: